# python-basic-utils travis config file

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

# @TODO: migrate to matrix below once 3.7 properly supported
#matrix:
#    include:
#        - python: 2.7
#          env: TOXENV=py27
#        - python: 3.5
#          env: TOXENV=py35
#        - python: 3.6
#          env: TOXENV=py36
#        - python: 3.7
#          env: TOXENV=py37

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    recipients:
      - amnon.janiv@ondalear.com

    on_success: change
    on_failure: always
  
branches:
  only:
    - master
    - develop