# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

# python:
# - "2.7"
# - "3.5"

#env:
#- TOXENV=py27
# - TOXENV=py35

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.5
          env: TOXENV=py35
       
install:
  - travis_retry pip install tox
script:
  - travis_retry tox
notifications:
  email:
    - pyramid-checkins@lists.repoze.org


install: pip install tox

script: tox

notifications:
  email:
    recipients:
      - amnon.janiv@ondalear.com

    on_success: change
    on_failure: always
  
branches:
  only:
    - master
    - develop